### ISSUE TITLE
Consider using node-webcrypto-ossl

### ISSUE THREAD

**Issue by rmhrisk** [Daplie/node-letsencrypt#19] opened 2016-02-16 02:12 UTC
Go ahead and close this but thought you might find this interesting:

https://github.com/PeculiarVentures/node-webcrypto-ossl

Its a polyfill for webcrypto based on OpenSSL that is designed for node.

This with https://pkijs.org/examples/PKCS10_complex_example.html would give you your crypto and cert stuff.

I can't sell the benefits over your current approach snce this probably would not be useful to work in both the browser and in node but either way might be interesting to be aware of.

**Comment by coolaj86** [comment] 2016-04-06 15:59
Sounds awesome actually.

I'll wait until it has docs for which polyfills are implemented and whatnot and then take a look.

Netflix also has one of these (and there are a few others), but the problem is that they (obviously) can't implement all of the 600 various WebCrypto functions at once and most of them are missing one aspect or another.

I'd really like to find one that has *working* ECDSA support (and there probably is one since I last googled and tried demos).

**Comment by coolaj86** [comment] 2016-08-09 23:24
Moving this discussion to https://github.com/Daplie/rsa-compat.js/issues/3

The `rsa-compat` library is pretty small and I'd love if you'd take a look and see if you think it's feasible to use pkijs in place of forge.

**Closed by coolaj86** 2016-08-09 23:24 UTC
Labels: enhancement, help wanted
